name: Python application test with Github Actions using devcontainers
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies-Build and run dev container task
      uses: devcontainers/ci@v0.2
      with:
        runCmd: |
          make install
    - name: Lint with pylint-Build and run dev container task
      uses: devcontainers/ci@v0.2
      with:
        runCmd: |
          make lint
    - name: Test with pytest-Build and run dev container task
      uses: devcontainers/ci@v0.2
      with:
        runCmd: |
          make test
